# Again stolen straight from https://github.com/lujjjh/LitoMusic/blob/main/.github/workflows/update-developer-token.yml
name: Update developer token
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-developer-token:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: scripts/getDevToken.sh
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v5.0.2
        with:
          commit-message: '[Automated] Update developer token'
          delete-branch: true
          base: trunk
          title: '[Automated] Update developer token'
      - name: Merge pull request
        if: steps.cpr.outputs.pull-request-operation == 'created'
        uses: juliangruber/merge-pull-request-action@v1.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ steps.cpr.outputs.pull-request-number }}
          method: squash